accounts = {
    'NZ': {'username': 'newnewzealand@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=nzd', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=nzd'},
    'AU': {'username': 'newaustralia@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillywin17.com/', 'deposit_url': 'https://www.kingbillywin17.com/profile/wallet/deposit?currency=aud', 'withdrawal_url': 'https://www.kingbillywin17.com/profile/wallet/withdrawal?currency=aud'},
    'AT': {'username': 'newaustria@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'CH': {'username': 'newswitzerland@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'IE': {'username': 'newireland@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'NO': {'username': 'newnorway@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'CY': {'username': 'newcyprus@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'DE': {'username': 'newdenmark@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'ZA': {'username':'newsouthafrica@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=zar', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=zar'},
    'IS': {'username': 'newiceland@kingbilly.xyz', 'password': 'KingBilly123!', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'KR': {'username': 'skorea@kingbilly.xyz', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'MX': {'username':'mexico@kingbilly.xyz', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'CA': {'username': 'canada@kingbilly.xyz', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=cad', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=cad'},
    'DK': {'username': 'denmark@kingbilly.xyz', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
}

accounts_old = {
    'NZ': {'username': 'newzealand@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=nzd', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=nzd'},
    'AU': {'username': 'australia@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillywin17.com/', 'deposit_url': 'https://www.kingbillywin17.com/profile/wallet/deposit?currency=aud', 'withdrawal_url': 'https://www.kingbillywin17.com/profile/wallet/withdrawal?currency=aud'},
    'AT': {'username': 'austria@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'CH': {'username': 'switzerland@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'IE': {'username': 'ireland@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'NO': {'username': 'norway@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'CY': {'username': 'cyprus@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'DE': {'username': 'denmark@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino9.com/', 'deposit_url': 'https://www.kingbillycasino9.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino9.com/profile/wallet/withdrawal?currency=eur'},
    'ZA': {'username':'southafrica@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=zar', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=zar'},
    'IS': {'username': 'iceland@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'KR': {'username': 'korea@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'MX': {'username':'mexico@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
    'CA': {'username': 'canada@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=cad', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=cad'},
    'DK': {'username': 'denmark@loshara.com', 'password': 'LOL12lol', 'url':'https://www.kingbillycasino.com/', 'deposit_url': 'https://www.kingbillycasino.com/profile/wallet/deposit?currency=eur', 'withdrawal_url': 'https://www.kingbillycasino.com/profile/wallet/withdrawal?currency=eur'},
}

url = 'https://kingbillycasino.com/'
wallet_url_deposit = 'https://www.kingbillycasino.com/profile/wallet/deposit'
wallet_url_withdrawal = 'https://www.kingbillycasino.com/profile/wallet/withdrawal'

browser_config = {
    "headless": False,  # Run browser in headless mode or not
    "viewport": {"width": 1920, "height": 1080},  # Default viewport size
}